openapi: 3.0.3
info:
  title: Order Service API
  description: Order Service for managing customer orders
  version: 1.0.0
  contact:
    name: Order Service Team

servers:
  - url: https://api.example.com
    description: Production server
  - url: https://api-staging.example.com
    description: Staging server

tags:
  - name: Orders
    description: Order management operations

paths:
  /api/v1/orders:
    post:
      tags:
        - Orders
      summary: Create a new order
      description: Creates a new order with the provided items
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      tags:
        - Orders
      summary: List orders
      description: Retrieve a paginated list of orders
      operationId: listOrders
      parameters:
        - name: pageNumber
          in: query
          description: Page number (1-based)
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            default: 1
        - name: pageSize
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 20
        - name: status
          in: query
          description: Filter by order status
          required: false
          schema:
            $ref: '#/components/schemas/OrderStatus'
        - name: customerId
          in: query
          description: Filter by customer ID
          required: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Orders retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/orders/{orderId}:
    get:
      tags:
        - Orders
      summary: Get order by ID
      description: Retrieve detailed information about a specific order
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          description: Unique identifier of the order
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/orders/{orderId}/status:
    patch:
      tags:
        - Orders
      summary: Update order status
      description: Update the status of an existing order
      operationId: updateOrderStatus
      parameters:
        - name: orderId
          in: path
          description: Unique identifier of the order
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOrderStatusRequest'
      responses:
        '200':
          description: Order status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Order:
      type: object
      required:
        - orderId
        - customerId
        - orderDate
        - status
        - totalAmount
        - items
      properties:
        orderId:
          type: string
          format: uuid
          description: Unique identifier of the order
        customerId:
          type: string
          format: uuid
          description: Unique identifier of the customer
        orderDate:
          type: string
          format: date-time
          description: Date and time when the order was created
        status:
          $ref: '#/components/schemas/OrderStatus'
        totalAmount:
          type: number
          format: decimal
          minimum: 0
          description: Total amount of the order
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderItem'
          description: List of items in the order

    OrderItem:
      type: object
      required:
        - orderItemId
        - productId
        - productName
        - quantity
        - unitPrice
        - totalPrice
      properties:
        orderItemId:
          type: string
          format: uuid
          description: Unique identifier of the order item
        productId:
          type: string
          format: uuid
          description: Unique identifier of the product
        productName:
          type: string
          minLength: 1
          maxLength: 200
          description: Name of the product
        quantity:
          type: integer
          format: int32
          minimum: 1
          description: Quantity of the product
        unitPrice:
          type: number
          format: decimal
          minimum: 0
          description: Price per unit
        totalPrice:
          type: number
          format: decimal
          minimum: 0
          description: Total price for this item (quantity * unitPrice)

    OrderStatus:
      type: string
      enum:
        - Pending
        - Confirmed
        - Shipped
        - Delivered
        - Cancelled
      description: Current status of the order

    CreateOrderRequest:
      type: object
      required:
        - customerId
        - items
      properties:
        customerId:
          type: string
          format: uuid
          description: Unique identifier of the customer placing the order
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/CreateOrderItemRequest'
          description: List of items to include in the order

    CreateOrderItemRequest:
      type: object
      required:
        - productId
        - quantity
      properties:
        productId:
          type: string
          format: uuid
          description: Unique identifier of the product
        quantity:
          type: integer
          format: int32
          minimum: 1
          description: Quantity of the product to order

    UpdateOrderStatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/OrderStatus'

    OrderListResponse:
      type: object
      required:
        - items
        - pageNumber
        - pageSize
        - totalCount
        - totalPages
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Order'
          description: List of orders for the current page
        pageNumber:
          type: integer
          format: int32
          minimum: 1
          description: Current page number
        pageSize:
          type: integer
          format: int32
          minimum: 1
          description: Number of items per page
        totalCount:
          type: integer
          format: int64
          minimum: 0
          description: Total number of orders
        totalPages:
          type: integer
          format: int32
          minimum: 0
          description: Total number of pages

    Error:
      type: object
      required:
        - traceId
        - code
        - message
      properties:
        traceId:
          type: string
          description: Unique identifier for tracing the error
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: string
          nullable: true
          description: Additional details about the error
        errors:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ValidationError'
          description: List of field-level validation errors

    ValidationError:
      type: object
      required:
        - field
        - message
      properties:
        field:
          type: string
          description: Name of the field that failed validation
        message:
          type: string
          description: Validation error message
